### ISSUE TITLE
Can't change TKCalendarCircleView color and no date is shown.

### ISSUE THREAD

**Issue by Morpheus2002** [maggix/tapkulibrary#1]
I can't change the color of TKCalendarCircleView. It's always black with no date inside. But the dot is shown correct.

BTW, I can't run the calendar demo from your fork. The app always cashes.

**Comment by Morpheus2002** [comment]
Still wasn't able to figure out how to set TKCalendarCircleView color. BTW, can't set the color in demo project too.

**Comment by maggix** [comment]
Hi, I should have fixed the issue with the Demo and allow to make the changes to the circle color. 
Sorry for keeping you waiting

**Comment by Morpheus2002** [comment]
@maggix Thanks! Now it works perfect!
